# Utilize a imagem base com JDK 17
FROM openjdk:17-jdk-slim

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie o JAR gerado pelo Maven para o container
COPY backend/target/*.jar app.jar

# Exponha a porta usada pela aplicação
EXPOSE 8080

# Defina o comando para rodar o JAR
ENTRYPOINT ["java", "-jar", "app.jar"]
